/* テストケース : A 数式エンジン / B 組み込み関数 */
const L = require('./lib');
const { calc } = L;

module.exports = [
/* ---------- A. 数式エンジン(演算子・優先順位・型変換) ---------- */
{ id:'TC-A-001', cat:'数式エンジン', view:'四則演算と優先順位', tech:'正常系', pre:'-', step:'=1+2*3 を入力', exp:'7', run:()=>calc({}, '=1+2*3') },
{ id:'TC-A-002', cat:'数式エンジン', view:'括弧による優先順位の上書き', tech:'正常系', pre:'-', step:'=(1+2)*3 を入力', exp:'9', run:()=>calc({}, '=(1+2)*3') },
{ id:'TC-A-003', cat:'数式エンジン', view:'べき乗の結合則(Excelは左結合)', tech:'境界値', pre:'-', step:'=2^3^2 を入力', exp:'64', run:()=>calc({}, '=2^3^2') },
{ id:'TC-A-004', cat:'数式エンジン', view:'単項マイナスとべき乗の優先順位', tech:'境界値', pre:'-', step:'=-2^2 を入力', exp:'4', run:()=>calc({}, '=-2^2') },
{ id:'TC-A-005', cat:'数式エンジン', view:'割り算(小数結果)', tech:'正常系', pre:'-', step:'=10/4 を入力', exp:'2.5', run:()=>calc({}, '=10/4') },
{ id:'TC-A-006', cat:'数式エンジン', view:'パーセント演算子', tech:'正常系', pre:'-', step:'=50% を入力', exp:'0.5', run:()=>calc({}, '=50%') },
{ id:'TC-A-007', cat:'数式エンジン', view:'文字列連結演算子', tech:'正常系', pre:'A1=abc', step:'=A1&123 を入力', exp:'abc123', run:()=>calc({A1:'abc'}, '=A1&123') },
{ id:'TC-A-008', cat:'数式エンジン', view:'数値に見える文字列の暗黙変換', tech:'同値分割', pre:'-', step:'="1"+1 を入力', exp:'2', run:()=>calc({}, '="1"+1') },
{ id:'TC-A-009', cat:'数式エンジン', view:'数値化できない文字列の演算', tech:'異常系', pre:'-', step:'="abc"+1 を入力', exp:'#VALUE!', run:()=>calc({}, '="abc"+1') },
{ id:'TC-A-010', cat:'数式エンジン', view:'論理値の数値化(TRUE=1)', tech:'同値分割', pre:'-', step:'=TRUE()+1 を入力', exp:'2', run:()=>calc({}, '=TRUE()+1') },
{ id:'TC-A-011', cat:'数式エンジン', view:'空セル参照は0として扱う', tech:'境界値', pre:'A1は空', step:'=A1+5 を入力', exp:'5', run:()=>calc({}, '=A1+5') },
{ id:'TC-A-012', cat:'数式エンジン', view:'空セルの文字列連結は空文字', tech:'境界値', pre:'A1は空', step:'=A1&"x" を入力', exp:'x', run:()=>calc({}, '=A1&"x"') },
{ id:'TC-A-013', cat:'数式エンジン', view:'比較演算子(等号)', tech:'正常系', pre:'-', step:'=1=1 を入力', exp:'TRUE', run:()=>calc({}, '=1=1') },
{ id:'TC-A-014', cat:'数式エンジン', view:'比較演算子(不等号)', tech:'正常系', pre:'-', step:'=2<>2 を入力', exp:'FALSE', run:()=>calc({}, '=2<>2') },
{ id:'TC-A-015', cat:'数式エンジン', view:'文字列比較(辞書順)', tech:'正常系', pre:'-', step:'="a"<"b" を入力', exp:'TRUE', run:()=>calc({}, '="a"<"b"') },
{ id:'TC-A-016', cat:'数式エンジン', view:'文字列比較は大文字小文字を区別しない', tech:'エラー推測', pre:'-', step:'="A"="a" を入力', exp:'TRUE', run:()=>calc({}, '="A"="a"') },
{ id:'TC-A-017', cat:'数式エンジン', view:'二重引用符のエスケープ', tech:'境界値', pre:'-', step:'="a""b" を入力', exp:'a"b', run:()=>calc({}, '="a""b"') },
{ id:'TC-A-018', cat:'数式エンジン', view:'指数表記リテラル', tech:'境界値', pre:'-', step:'=1.5e3 を入力', exp:'1500', run:()=>calc({}, '=1.5e3') },
{ id:'TC-A-019', cat:'数式エンジン', view:'関数の入れ子(3段)', tech:'正常系', pre:'A1=-4', step:'=ROUND(SQRT(ABS(A1)),1) を入力', exp:'2', run:()=>calc({A1:-4}, '=ROUND(SQRT(ABS(A1)),1)') },
{ id:'TC-A-020', cat:'数式エンジン', view:'0.1+0.2の浮動小数点誤差が表示に出ないこと', tech:'エラー推測', pre:'-', step:'=0.1+0.2 を入力', exp:'0.3', run:()=>calc({}, '=0.1+0.2') },

/* ---------- B. 組み込み関数 ---------- */
{ id:'TC-B-001', cat:'関数(統計)', view:'SUM 範囲指定', tech:'正常系', pre:'A1:A3=1,2,3', step:'=SUM(A1:A3)', exp:'6', run:()=>calc({A1:1,A2:2,A3:3}, '=SUM(A1:A3)') },
{ id:'TC-B-002', cat:'関数(統計)', view:'SUM 範囲内の文字列は無視される', tech:'同値分割', pre:'A1=1,A2=abc,A3=3', step:'=SUM(A1:A3)', exp:'4', run:()=>calc({A1:1,A2:'abc',A3:3}, '=SUM(A1:A3)') },
{ id:'TC-B-003', cat:'関数(統計)', view:'SUM 直接引数の文字列は数値化される', tech:'同値分割', pre:'-', step:'=SUM(1,"2")', exp:'3', run:()=>calc({}, '=SUM(1,"2")') },
{ id:'TC-B-004', cat:'関数(統計)', view:'SUM 空範囲は0', tech:'境界値', pre:'A1:A3は空', step:'=SUM(A1:A3)', exp:'0', run:()=>calc({}, '=SUM(A1:A3)') },
{ id:'TC-B-005', cat:'関数(統計)', view:'AVERAGE 文字列を除いた平均', tech:'同値分割', pre:'A1=1,A2=abc,A3=3', step:'=AVERAGE(A1:A3)', exp:'2', run:()=>calc({A1:1,A2:'abc',A3:3}, '=AVERAGE(A1:A3)') },
{ id:'TC-B-006', cat:'関数(統計)', view:'AVERAGE 対象0件は#DIV/0!', tech:'異常系', pre:'A1:A3は空', step:'=AVERAGE(A1:A3)', exp:'#DIV/0!', run:()=>calc({}, '=AVERAGE(A1:A3)') },
{ id:'TC-B-007', cat:'関数(統計)', view:'COUNT は数値のみ数える', tech:'同値分割', pre:'A1=1,A2=abc,A3=3', step:'=COUNT(A1:A3)', exp:'2', run:()=>calc({A1:1,A2:'abc',A3:3}, '=COUNT(A1:A3)') },
{ id:'TC-B-008', cat:'関数(統計)', view:'COUNTA は空以外を数える', tech:'同値分割', pre:'A1=1,A2=abc,A3は空', step:'=COUNTA(A1:A3)', exp:'2', run:()=>calc({A1:1,A2:'abc'}, '=COUNTA(A1:A3)') },
{ id:'TC-B-009', cat:'関数(統計)', view:'COUNTBLANK は空セルを数える', tech:'境界値', pre:'A1=1,A2,A3は空', step:'=COUNTBLANK(A1:A3)', exp:'2', run:()=>calc({A1:1}, '=COUNTBLANK(A1:A3)') },
{ id:'TC-B-010', cat:'関数(統計)', view:'MAX 全空のとき0', tech:'境界値', pre:'A1:A3は空', step:'=MAX(A1:A3)', exp:'0', run:()=>calc({}, '=MAX(A1:A3)') },
{ id:'TC-B-011', cat:'関数(統計)', view:'MEDIAN 偶数個は中央2値の平均', tech:'境界値', pre:'A1:A4=1,2,3,4', step:'=MEDIAN(A1:A4)', exp:'2.5', run:()=>calc({A1:1,A2:2,A3:3,A4:4}, '=MEDIAN(A1:A4)') },
{ id:'TC-B-012', cat:'関数(統計)', view:'STDEV(標本標準偏差)', tech:'正常系', pre:'A1:A4=2,4,4,6', step:'=ROUND(STDEV(A1:A4),4)', exp:'1.633', run:()=>calc({A1:2,A2:4,A3:4,A4:6}, '=ROUND(STDEV(A1:A4),4)') },
{ id:'TC-B-013', cat:'関数(統計)', view:'STDEVP(母標準偏差)', tech:'正常系', pre:'A1:A4=2,4,4,6', step:'=ROUND(STDEVP(A1:A4),4)', exp:'1.4142', run:()=>calc({A1:2,A2:4,A3:4,A4:6}, '=ROUND(STDEVP(A1:A4),4)') },
{ id:'TC-B-014', cat:'関数(統計)', view:'LARGE のn番目', tech:'正常系', pre:'A1:A4=5,1,4,2', step:'=LARGE(A1:A4,2)', exp:'4', run:()=>calc({A1:5,A2:1,A3:4,A4:2}, '=LARGE(A1:A4,2)') },
{ id:'TC-B-015', cat:'関数(統計)', view:'RANK 降順の順位', tech:'正常系', pre:'A1:A4=5,1,4,2', step:'=RANK(4,A1:A4)', exp:'2', run:()=>calc({A1:5,A2:1,A3:4,A4:2}, '=RANK(4,A1:A4)') },
{ id:'TC-B-016', cat:'関数(条件集計)', view:'COUNTIF 比較演算子つき条件', tech:'正常系', pre:'A1:A5=1,5,10,15,20', step:'=COUNTIF(A1:A5,">=10")', exp:'3', run:()=>calc({A1:1,A2:5,A3:10,A4:15,A5:20}, '=COUNTIF(A1:A5,">=10")') },
{ id:'TC-B-017', cat:'関数(条件集計)', view:'COUNTIF ワイルドカード', tech:'正常系', pre:'A1=apple,A2=apricot,A3=banana', step:'=COUNTIF(A1:A3,"ap*")', exp:'2', run:()=>calc({A1:'apple',A2:'apricot',A3:'banana'}, '=COUNTIF(A1:A3,"ap*")') },
{ id:'TC-B-018', cat:'関数(条件集計)', view:'SUMIF 合計範囲を別指定', tech:'正常系', pre:'A1:A3=x,y,x / B1:B3=1,2,3', step:'=SUMIF(A1:A3,"x",B1:B3)', exp:'4', run:()=>calc({A1:'x',A2:'y',A3:'x',B1:1,B2:2,B3:3}, '=SUMIF(A1:A3,"x",B1:B3)') },
{ id:'TC-B-019', cat:'関数(条件集計)', view:'SUMIFS 複数条件のAND', tech:'デシジョンテーブル', pre:'A=部署,B=月,C=金額', step:'=SUMIFS(C1:C4,A1:A4,"営業",B1:B4,4)', exp:'300', run:()=>calc({A1:'営業',B1:4,C1:100,A2:'営業',B2:5,C2:200,A3:'営業',B3:4,C3:200,A4:'開発',B4:4,C4:900}, '=SUMIFS(C1:C4,A1:A4,"営業",B1:B4,4)') },
{ id:'TC-B-020', cat:'関数(条件集計)', view:'COUNTIFS 複数条件のAND', tech:'デシジョンテーブル', pre:'A=部署,B=月', step:'=COUNTIFS(A1:A4,"営業",B1:B4,4)', exp:'2', run:()=>calc({A1:'営業',B1:4,A2:'営業',B2:5,A3:'営業',B3:4,A4:'開発',B4:4}, '=COUNTIFS(A1:A4,"営業",B1:B4,4)') },
{ id:'TC-B-021', cat:'関数(条件集計)', view:'AVERAGEIF 条件つき平均', tech:'正常系', pre:'A1:A3=x,y,x / B=10,99,20', step:'=AVERAGEIF(A1:A3,"x",B1:B3)', exp:'15', run:()=>calc({A1:'x',A2:'y',A3:'x',B1:10,B2:99,B3:20}, '=AVERAGEIF(A1:A3,"x",B1:B3)') },
{ id:'TC-B-022', cat:'関数(論理)', view:'IF 真の分岐', tech:'デシジョンテーブル', pre:'A1=5', step:'=IF(A1>3,"大","小")', exp:'大', run:()=>calc({A1:5}, '=IF(A1>3,"大","小")') },
{ id:'TC-B-023', cat:'関数(論理)', view:'IF 偽の分岐', tech:'デシジョンテーブル', pre:'A1=1', step:'=IF(A1>3,"大","小")', exp:'小', run:()=>calc({A1:1}, '=IF(A1>3,"大","小")') },
{ id:'TC-B-024', cat:'関数(論理)', view:'IF 第3引数省略時はFALSE', tech:'境界値', pre:'A1=1', step:'=IF(A1>3,"大")', exp:'FALSE', run:()=>calc({A1:1}, '=IF(A1>3,"大")') },
{ id:'TC-B-025', cat:'関数(論理)', view:'AND/OR/NOT の組み合わせ', tech:'デシジョンテーブル', pre:'-', step:'=AND(TRUE(),OR(FALSE(),NOT(FALSE())))', exp:'TRUE', run:()=>calc({}, '=AND(TRUE(),OR(FALSE(),NOT(FALSE())))') },
{ id:'TC-B-026', cat:'関数(論理)', view:'XOR 排他的論理和', tech:'デシジョンテーブル', pre:'-', step:'=XOR(TRUE(),TRUE())', exp:'FALSE', run:()=>calc({}, '=XOR(TRUE(),TRUE())') },
{ id:'TC-B-027', cat:'関数(論理)', view:'IFS 最初に一致した条件を返す', tech:'デシジョンテーブル', pre:'A1=75', step:'=IFS(A1>=90,"A",A1>=70,"B",TRUE(),"C")', exp:'B', run:()=>calc({A1:75}, '=IFS(A1>=90,"A",A1>=70,"B",TRUE(),"C")') },
{ id:'TC-B-028', cat:'関数(論理)', view:'IFERROR エラー時の代替値', tech:'異常系', pre:'-', step:'=IFERROR(1/0,"エラー")', exp:'エラー', run:()=>calc({}, '=IFERROR(1/0,"エラー")') },
{ id:'TC-B-029', cat:'関数(論理)', view:'IFERROR 正常時は元の値', tech:'正常系', pre:'-', step:'=IFERROR(10/2,"エラー")', exp:'5', run:()=>calc({}, '=IFERROR(10/2,"エラー")') },
{ id:'TC-B-030', cat:'関数(論理)', view:'IFNA は#N/Aのみ捕捉する', tech:'エラー推測', pre:'-', step:'=IFNA(1/0,"NA")', exp:'#DIV/0!', run:()=>calc({}, '=IFNA(1/0,"NA")') },
{ id:'TC-B-031', cat:'関数(検索)', view:'VLOOKUP 完全一致', tech:'正常系', pre:'A1:B3 に商品表', step:'=VLOOKUP("B",A1:B3,2,FALSE)', exp:'200', run:()=>calc({A1:'A',B1:100,A2:'B',B2:200,A3:'C',B3:300}, '=VLOOKUP("B",A1:B3,2,FALSE())') },
{ id:'TC-B-032', cat:'関数(検索)', view:'VLOOKUP 該当なしは#N/A', tech:'異常系', pre:'A1:B3 に商品表', step:'=VLOOKUP("Z",A1:B3,2,FALSE)', exp:'#N/A', run:()=>calc({A1:'A',B1:100,A2:'B',B2:200,A3:'C',B3:300}, '=VLOOKUP("Z",A1:B3,2,FALSE())') },
{ id:'TC-B-033', cat:'関数(検索)', view:'VLOOKUP 近似一致(第4引数TRUE)', tech:'境界値', pre:'A=0,10,20 / B=低,中,高', step:'=VLOOKUP(15,A1:B3,2,TRUE)', exp:'中', run:()=>calc({A1:0,B1:'低',A2:10,B2:'中',A3:20,B3:'高'}, '=VLOOKUP(15,A1:B3,2,TRUE())') },
{ id:'TC-B-034', cat:'関数(検索)', view:'VLOOKUP 列番号が範囲外は#REF!', tech:'異常系', pre:'A1:B3 に表', step:'=VLOOKUP("A",A1:B3,5,FALSE)', exp:'#REF!', run:()=>calc({A1:'A',B1:100,A2:'B',B2:200,A3:'C',B3:300}, '=VLOOKUP("A",A1:B3,5,FALSE())') },
{ id:'TC-B-035', cat:'関数(検索)', view:'HLOOKUP 行方向の検索', tech:'正常系', pre:'A1:C2 に横持ちの表', step:'=HLOOKUP("B",A1:C2,2,FALSE)', exp:'20', run:()=>calc({A1:'A',B1:'B',C1:'C',A2:10,B2:20,C2:30}, '=HLOOKUP("B",A1:C2,2,FALSE())') },
{ id:'TC-B-036', cat:'関数(検索)', view:'INDEX 行列指定', tech:'正常系', pre:'A1:C3 に3x3', step:'=INDEX(A1:C3,2,3)', exp:'6', run:()=>calc({A1:1,B1:2,C1:3,A2:4,B2:5,C2:6,A3:7,B3:8,C3:9}, '=INDEX(A1:C3,2,3)') },
{ id:'TC-B-037', cat:'関数(検索)', view:'MATCH 完全一致の位置', tech:'正常系', pre:'A1:A3=x,y,z', step:'=MATCH("y",A1:A3,0)', exp:'2', run:()=>calc({A1:'x',A2:'y',A3:'z'}, '=MATCH("y",A1:A3,0)') },
{ id:'TC-B-038', cat:'関数(検索)', view:'INDEX+MATCH の組み合わせ', tech:'組み合わせ', pre:'A=キー,B=値', step:'=INDEX(B1:B3,MATCH("y",A1:A3,0))', exp:'20', run:()=>calc({A1:'x',B1:10,A2:'y',B2:20,A3:'z',B3:30}, '=INDEX(B1:B3,MATCH("y",A1:A3,0))') },
{ id:'TC-B-039', cat:'関数(検索)', view:'CHOOSE の分岐', tech:'正常系', pre:'-', step:'=CHOOSE(2,"a","b","c")', exp:'b', run:()=>calc({}, '=CHOOSE(2,"a","b","c")') },
{ id:'TC-B-040', cat:'関数(検索)', view:'ROWS/COLUMNS で範囲サイズ', tech:'正常系', pre:'-', step:'=ROWS(A1:C4)&"x"&COLUMNS(A1:C4)', exp:'4x3', run:()=>calc({}, '=ROWS(A1:C4)&"x"&COLUMNS(A1:C4)') },
{ id:'TC-B-041', cat:'関数(文字列)', view:'LEFT は全角も1文字扱い', tech:'境界値', pre:'-', step:'=LEFT("あいう",2)', exp:'あい', run:()=>calc({}, '=LEFT("あいう",2)') },
{ id:'TC-B-042', cat:'関数(文字列)', view:'LEN 全角文字数', tech:'境界値', pre:'-', step:'=LEN("あいう")', exp:'3', run:()=>calc({}, '=LEN("あいう")') },
{ id:'TC-B-043', cat:'関数(文字列)', view:'MID の開始位置', tech:'正常系', pre:'-', step:'=MID("abcdef",3,2)', exp:'cd', run:()=>calc({}, '=MID("abcdef",3,2)') },
{ id:'TC-B-044', cat:'関数(文字列)', view:'MID 開始位置0は#VALUE!', tech:'異常系', pre:'-', step:'=MID("abcdef",0,2)', exp:'#VALUE!', run:()=>calc({}, '=MID("abcdef",0,2)') },
{ id:'TC-B-045', cat:'関数(文字列)', view:'FIND は大文字小文字を区別する', tech:'同値分割', pre:'-', step:'=FIND("B","abc")', exp:'#VALUE!', run:()=>calc({}, '=FIND("B","abc")') },
{ id:'TC-B-046', cat:'関数(文字列)', view:'SEARCH は区別しない', tech:'同値分割', pre:'-', step:'=SEARCH("B","abc")', exp:'2', run:()=>calc({}, '=SEARCH("B","abc")') },
{ id:'TC-B-047', cat:'関数(文字列)', view:'SUBSTITUTE の全置換', tech:'正常系', pre:'-', step:'=SUBSTITUTE("a-b-c","-","/")', exp:'a/b/c', run:()=>calc({}, '=SUBSTITUTE("a-b-c","-","/")') },
{ id:'TC-B-048', cat:'関数(文字列)', view:'REPLACE の位置指定置換', tech:'正常系', pre:'-', step:'=REPLACE("abcdef",2,3,"X")', exp:'aXef', run:()=>calc({}, '=REPLACE("abcdef",2,3,"X")') },
{ id:'TC-B-049', cat:'関数(文字列)', view:'TRIM 前後空白の除去', tech:'境界値', pre:'-', step:'=TRIM("  a b  ")&"|"', exp:'a b|', run:()=>calc({}, '=TRIM("  a b  ")&"|"') },
{ id:'TC-B-050', cat:'関数(文字列)', view:'TEXTJOIN 空セルの扱い(TRUE=無視)', tech:'デシジョンテーブル', pre:'A1=a,A2は空,A3=c', step:'=TEXTJOIN("-",TRUE,A1:A3)', exp:'a-c', run:()=>calc({A1:'a',A3:'c'}, '=TEXTJOIN("-",TRUE(),A1:A3)') },
{ id:'TC-B-051', cat:'関数(文字列)', view:'EXACT は完全一致判定', tech:'同値分割', pre:'-', step:'=EXACT("A","a")', exp:'FALSE', run:()=>calc({}, '=EXACT("A","a")') },
{ id:'TC-B-052', cat:'関数(文字列)', view:'VALUE 文字列を数値化', tech:'正常系', pre:'-', step:'=VALUE("123")+1', exp:'124', run:()=>calc({}, '=VALUE("123")+1') },
{ id:'TC-B-053', cat:'関数(文字列)', view:'REPT の繰り返し', tech:'正常系', pre:'-', step:'=REPT("ab",3)', exp:'ababab', run:()=>calc({}, '=REPT("ab",3)') },
{ id:'TC-B-054', cat:'関数(数値)', view:'ROUND 四捨五入(正)', tech:'境界値', pre:'-', step:'=ROUND(2.5,0)', exp:'3', run:()=>calc({}, '=ROUND(2.5,0)') },
{ id:'TC-B-055', cat:'関数(数値)', view:'ROUND 負数は絶対値で四捨五入', tech:'境界値', pre:'-', step:'=ROUND(-2.5,0)', exp:'-3', run:()=>calc({}, '=ROUND(-2.5,0)') },
{ id:'TC-B-056', cat:'関数(数値)', view:'ROUND 桁数指定', tech:'正常系', pre:'-', step:'=ROUND(1.2345,2)', exp:'1.23', run:()=>calc({}, '=ROUND(1.2345,2)') },
{ id:'TC-B-057', cat:'関数(数値)', view:'ROUND 桁数が負(100の位で丸め)', tech:'境界値', pre:'-', step:'=ROUND(1234,-2)', exp:'1200', run:()=>calc({}, '=ROUND(1234,-2)') },
{ id:'TC-B-058', cat:'関数(数値)', view:'ROUNDUP 負数は絶対値で切り上げ', tech:'境界値', pre:'-', step:'=ROUNDUP(-1.1,0)', exp:'-2', run:()=>calc({}, '=ROUNDUP(-1.1,0)') },
{ id:'TC-B-059', cat:'関数(数値)', view:'ROUNDDOWN 負数は0方向へ切り捨て', tech:'境界値', pre:'-', step:'=ROUNDDOWN(-1.9,0)', exp:'-1', run:()=>calc({}, '=ROUNDDOWN(-1.9,0)') },
{ id:'TC-B-060', cat:'関数(数値)', view:'INT は負数で切り下げ', tech:'境界値', pre:'-', step:'=INT(-2.5)', exp:'-3', run:()=>calc({}, '=INT(-2.5)') },
{ id:'TC-B-061', cat:'関数(数値)', view:'TRUNC は0方向へ切り捨て', tech:'境界値', pre:'-', step:'=TRUNC(-2.9)', exp:'-2', run:()=>calc({}, '=TRUNC(-2.9)') },
{ id:'TC-B-062', cat:'関数(数値)', view:'MOD 除数が負のときの符号', tech:'境界値', pre:'-', step:'=MOD(-3,2)', exp:'1', run:()=>calc({}, '=MOD(-3,2)') },
{ id:'TC-B-063', cat:'関数(数値)', view:'MOD 除数0は#DIV/0!', tech:'異常系', pre:'-', step:'=MOD(5,0)', exp:'#DIV/0!', run:()=>calc({}, '=MOD(5,0)') },
{ id:'TC-B-064', cat:'関数(数値)', view:'CEILING 基準値の倍数へ切り上げ', tech:'正常系', pre:'-', step:'=CEILING(7,3)', exp:'9', run:()=>calc({}, '=CEILING(7,3)') },
{ id:'TC-B-065', cat:'関数(数値)', view:'FLOOR 基準値の倍数へ切り下げ', tech:'正常系', pre:'-', step:'=FLOOR(7,3)', exp:'6', run:()=>calc({}, '=FLOOR(7,3)') },
{ id:'TC-B-066', cat:'関数(数値)', view:'SQRT 負数は#NUM!', tech:'異常系', pre:'-', step:'=SQRT(-1)', exp:'#NUM!', run:()=>calc({}, '=SQRT(-1)') },
{ id:'TC-B-067', cat:'関数(数値)', view:'POWER と ^ の一致', tech:'正常系', pre:'-', step:'=POWER(2,10)', exp:'1024', run:()=>calc({}, '=POWER(2,10)') },
{ id:'TC-B-068', cat:'関数(数値)', view:'SUMPRODUCT 対応要素の積和', tech:'正常系', pre:'A=1,2,3 / B=4,5,6', step:'=SUMPRODUCT(A1:A3,B1:B3)', exp:'32', run:()=>calc({A1:1,A2:2,A3:3,B1:4,B2:5,B3:6}, '=SUMPRODUCT(A1:A3,B1:B3)') },
{ id:'TC-B-069', cat:'関数(数値)', view:'QUOTIENT 商の整数部', tech:'正常系', pre:'-', step:'=QUOTIENT(7,2)', exp:'3', run:()=>calc({}, '=QUOTIENT(7,2)') },
{ id:'TC-B-070', cat:'関数(情報)', view:'ISBLANK 空セル判定', tech:'境界値', pre:'A1は空', step:'=ISBLANK(A1)', exp:'TRUE', run:()=>calc({}, '=ISBLANK(A1)') },
{ id:'TC-B-071', cat:'関数(情報)', view:'ISNUMBER 数値判定', tech:'同値分割', pre:'A1=abc', step:'=ISNUMBER(A1)', exp:'FALSE', run:()=>calc({A1:'abc'}, '=ISNUMBER(A1)') },
{ id:'TC-B-072', cat:'関数(情報)', view:'ISERROR エラー判定', tech:'異常系', pre:'-', step:'=ISERROR(1/0)', exp:'TRUE', run:()=>calc({}, '=ISERROR(1/0)') },
{ id:'TC-B-073', cat:'関数(日付)', view:'DATE から YEAR/MONTH/DAY の往復', tech:'正常系', pre:'-', step:'=YEAR(DATE(2026,8,23))&"/"&MONTH(...)&"/"&DAY(...)', exp:'2026/8/23', run:()=>calc({}, '=YEAR(DATE(2026,8,23))&"/"&MONTH(DATE(2026,8,23))&"/"&DAY(DATE(2026,8,23))') },
{ id:'TC-B-074', cat:'関数(日付)', view:'DATE 月の繰り上がり(13月)', tech:'境界値', pre:'-', step:'=YEAR(DATE(2026,13,1))', exp:'2027', run:()=>calc({}, '=YEAR(DATE(2026,13,1))') },
{ id:'TC-B-075', cat:'関数(日付)', view:'うるう年 2/29 の判定', tech:'境界値', pre:'-', step:'=DAY(DATE(2024,2,29))', exp:'29', run:()=>calc({}, '=DAY(DATE(2024,2,29))') },
{ id:'TC-B-076', cat:'関数(日付)', view:'DATEDIF 年数差', tech:'正常系', pre:'-', step:'=DATEDIF(DATE(2020,1,1),DATE(2026,8,23),"Y")', exp:'6', run:()=>calc({}, '=DATEDIF(DATE(2020,1,1),DATE(2026,8,23),"Y")') },
{ id:'TC-B-077', cat:'関数(日付)', view:'DATEDIF 日数差', tech:'正常系', pre:'-', step:'=DATEDIF(DATE(2026,1,1),DATE(2026,1,31),"D")', exp:'30', run:()=>calc({}, '=DATEDIF(DATE(2026,1,1),DATE(2026,1,31),"D")') },
{ id:'TC-B-078', cat:'関数(日付)', view:'EOMONTH 当月末(2月28日)', tech:'境界値', pre:'-', step:'=DAY(EOMONTH(DATE(2026,2,10),0))', exp:'28', run:()=>calc({}, '=DAY(EOMONTH(DATE(2026,2,10),0))') },
{ id:'TC-B-079', cat:'関数(日付)', view:'EDATE 翌月同日(月末補正)', tech:'境界値', pre:'-', step:'=DAY(EDATE(DATE(2026,1,31),1))', exp:'28', run:()=>calc({}, '=DAY(EDATE(DATE(2026,1,31),1))') },
{ id:'TC-B-080', cat:'関数(日付)', view:'WEEKDAY 日曜=1', tech:'境界値', pre:'2026/8/23は日曜', step:'=WEEKDAY(DATE(2026,8,23))', exp:'1', run:()=>calc({}, '=WEEKDAY(DATE(2026,8,23))') },
{ id:'TC-B-081', cat:'関数(日付)', view:'DAYS 日数差', tech:'正常系', pre:'-', step:'=DAYS(DATE(2026,3,1),DATE(2026,2,1))', exp:'28', run:()=>calc({}, '=DAYS(DATE(2026,3,1),DATE(2026,2,1))') },
{ id:'TC-B-082', cat:'関数(日付)', view:'TIME の時刻シリアル値', tech:'正常系', pre:'-', step:'=HOUR(TIME(13,30,0))&":"&MINUTE(TIME(13,30,0))', exp:'13:30', run:()=>calc({}, '=HOUR(TIME(13,30,0))&":"&MINUTE(TIME(13,30,0))') },
{ id:'TC-B-083', cat:'関数(財務)', view:'PMT 毎月返済額', tech:'正常系', pre:'年利2%/120回/1000万', step:'=ROUND(PMT(0.02/12,120,10000000),0)', exp:'-92013', run:()=>calc({}, '=ROUND(PMT(0.02/12,120,10000000),0)') },
{ id:'TC-B-084', cat:'関数(財務)', view:'FV 将来価値', tech:'正常系', pre:'年利1%/10年/毎年10万積立', step:'=ROUND(FV(0.01,10,-100000,0),0)', exp:'1046221', run:()=>calc({}, '=ROUND(FV(0.01,10,-100000,0),0)') },
{ id:'TC-B-085', cat:'関数(財務)', view:'PV 現在価値', tech:'正常系', pre:'年利1%/10年/毎年10万受取', step:'=ROUND(PV(0.01,10,-100000,0),0)', exp:'947130', run:()=>calc({}, '=ROUND(PV(0.01,10,-100000,0),0)') },
{ id:'TC-B-086', cat:'関数(文字列)', view:'TEXT 桁区切り書式', tech:'正常系', pre:'-', step:'=TEXT(1234567,"#,##0")', exp:'1,234,567', run:()=>calc({}, '=TEXT(1234567,"#,##0")') },
{ id:'TC-B-087', cat:'関数(文字列)', view:'TEXT パーセント書式', tech:'正常系', pre:'-', step:'=TEXT(0.256,"0.0%")', exp:'25.6%', run:()=>calc({}, '=TEXT(0.256,"0.0%")') },
{ id:'TC-B-088', cat:'関数(文字列)', view:'TEXT 日付書式', tech:'正常系', pre:'-', step:'=TEXT(DATE(2026,8,5),"yyyy/mm/dd")', exp:'2026/08/05', run:()=>calc({}, '=TEXT(DATE(2026,8,5),"yyyy/mm/dd")') },
];
